baseURL = "https://tejinder-addminweb.github.io/repblog/"
languageCode = "en-us"
title = "repblog"
theme = "ananke"

[permalinks]
  posts = "/posts/:filename/"

[params]
  description = ""
  show_reading_time = true
  mainSections = ["posts"]
  recent_posts_number = 3
  
[params.ananke]
  show_recent_posts = true
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2